pub mod io_gba_read {
        use advancedslop_macros::io_read;
    io_read!(
        (io16(0x0), |emu| emu.gpu.get_disp_cnt()),
        (io16(0x2), |emu| emu.gpu.green_swap),
        (io16(0x4), |emu| emu.gpu.get_disp_stat()),
        (io16(0x6), |emu| emu.gpu.v_count),
        (io16(0x8), |emu| emu.gpu.ppu.bg_cnt[0]),
        (io16(0xA), |emu| emu.gpu.ppu.bg_cnt[1]),
        (io16(0xC), |emu| emu.gpu.ppu.bg_cnt[2]),
        (io16(0xE), |emu| emu.gpu.ppu.bg_cnt[3]),
        (io16(0x48), |emu| emu.gpu.ppu.win_in),
        (io16(0x4A), |emu| emu.gpu.ppu.win_out),
        (io16(0x50), |emu| emu.gpu.ppu.bld_cnt),
        (io16(0x52), |emu| emu.gpu.ppu.bld_alpha),
        (io16(0x60), |emu| emu.apu.read_cnt_l(0) as u16),
        (io16(0x62), |emu| emu.apu.read_cnt_h(0)),
        (io16(0x64), |emu| emu.apu.read_cnt_x(0)),
        (io16(0x68), |emu| emu.apu.read_cnt_h(1)),
        (io16(0x6C), |emu| emu.apu.read_cnt_x(1)),
        (io16(0x70), |emu| emu.apu.read_cnt_l(2) as u16),
        (io16(0x72), |emu| emu.apu.read_cnt_h(2)),
        (io16(0x74), |emu| emu.apu.read_cnt_x(2)),
        (io16(0x78), |emu| emu.apu.read_cnt_h(3)),
        (io16(0x7C), |emu| emu.apu.read_cnt_x(3)),
        (io16(0x80), |emu| emu.apu.read_main_cnt_l()),
        (io16(0x82), |emu| emu.apu.read_main_cnt_h()),
        (io16(0x84), |emu| emu.apu.read_main_cnt_x() as u16),
        (io16(0x88), |emu| emu.apu.sound_bias),
        (io8(0x90), |emu| emu.apu.read_wave_ram(0)),
        (io8(0x91), |emu| emu.apu.read_wave_ram(1)),
        (io8(0x92), |emu| emu.apu.read_wave_ram(2)),
        (io8(0x93), |emu| emu.apu.read_wave_ram(3)),
        (io8(0x94), |emu| emu.apu.read_wave_ram(4)),
        (io8(0x95), |emu| emu.apu.read_wave_ram(5)),
        (io8(0x96), |emu| emu.apu.read_wave_ram(6)),
        (io8(0x97), |emu| emu.apu.read_wave_ram(7)),
        (io8(0x98), |emu| emu.apu.read_wave_ram(8)),
        (io8(0x99), |emu| emu.apu.read_wave_ram(9)),
        (io8(0x9A), |emu| emu.apu.read_wave_ram(10)),
        (io8(0x9B), |emu| emu.apu.read_wave_ram(11)),
        (io8(0x9C), |emu| emu.apu.read_wave_ram(12)),
        (io8(0x9D), |emu| emu.apu.read_wave_ram(13)),
        (io8(0x9E), |emu| emu.apu.read_wave_ram(14)),
        (io8(0x9F), |emu| emu.apu.read_wave_ram(15)),
        (io32(0xB8), |emu| emu.dma_get_cnt(0) & !0xFFFF),
        (io32(0xC4), |emu| emu.dma_get_cnt(1) & !0xFFFF),
        (io32(0xD0), |emu| emu.dma_get_cnt(2) & !0xFFFF),
        (io32(0xDC), |emu| emu.dma_get_cnt(3) & !0xFFFF),
        (io16(0x100), |emu| emu.timers_get_cnt_l(0)),
        (io16(0x102), |emu| emu.timers_get_cnt_h(0)),
        (io16(0x104), |emu| emu.timers_get_cnt_l(1)),
        (io16(0x106), |emu| emu.timers_get_cnt_h(1)),
        (io16(0x108), |emu| emu.timers_get_cnt_l(2)),
        (io16(0x10A), |emu| emu.timers_get_cnt_h(2)),
        (io16(0x10C), |emu| emu.timers_get_cnt_l(3)),
        (io16(0x10E), |emu| emu.timers_get_cnt_h(3)),
        (io16(0x130), |emu| emu.input.get_key_input()),
        (io16(0x132), |emu| emu.input.key_cnt),
        (io16(0x200), |emu| crate::core::thread_regs().ie as u16),
        (io16(0x202), |emu| crate::core::thread_regs().irf as u16),
        (io16(0x204), |emu| emu.cpu.wait_cnt),
        (io8(0x208), |emu| crate::core::thread_regs().ime),
        (io8(0x300), |emu| emu.cpu.post_flg),
        (io8(0x301), |emu| emu.cpu.halt_cnt),
    );
}

pub mod io_gba_write {
        use advancedslop_macros::io_write;
    io_write!(
        (io16(0x0), |mask, value, emu| emu.gpu.set_disp_cnt(mask, value)),
        (io16(0x2), |mask, value, emu| emu.gpu.green_swap = (emu.gpu.green_swap & !mask) | (value & mask)),
        (io16(0x4), |mask, value, emu| emu.gpu.set_disp_stat(mask, value)),
        (io16(0x8), |mask, value, emu| emu.gpu.ppu.bg_cnt[0] = (emu.gpu.ppu.bg_cnt[0] & !(mask & 0xDFFF)) | (value & mask & 0xDFFF)),
        (io16(0xA), |mask, value, emu| emu.gpu.ppu.bg_cnt[1] = (emu.gpu.ppu.bg_cnt[1] & !(mask & 0xDFFF)) | (value & mask & 0xDFFF)),
        (io16(0xC), |mask, value, emu| emu.gpu.ppu.bg_cnt[2] = (emu.gpu.ppu.bg_cnt[2] & !mask) | (value & mask)),
        (io16(0xE), |mask, value, emu| emu.gpu.ppu.bg_cnt[3] = (emu.gpu.ppu.bg_cnt[3] & !mask) | (value & mask)),
        (io16(0x10), |mask, value, emu| emu.gpu.ppu.bg_h_ofs[0] = (emu.gpu.ppu.bg_h_ofs[0] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x12), |mask, value, emu| emu.gpu.ppu.bg_v_ofs[0] = (emu.gpu.ppu.bg_v_ofs[0] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x14), |mask, value, emu| emu.gpu.ppu.bg_h_ofs[1] = (emu.gpu.ppu.bg_h_ofs[1] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x16), |mask, value, emu| emu.gpu.ppu.bg_v_ofs[1] = (emu.gpu.ppu.bg_v_ofs[1] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x18), |mask, value, emu| emu.gpu.ppu.bg_h_ofs[2] = (emu.gpu.ppu.bg_h_ofs[2] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x1A), |mask, value, emu| emu.gpu.ppu.bg_v_ofs[2] = (emu.gpu.ppu.bg_v_ofs[2] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x1C), |mask, value, emu| emu.gpu.ppu.bg_h_ofs[3] = (emu.gpu.ppu.bg_h_ofs[3] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x1E), |mask, value, emu| emu.gpu.ppu.bg_v_ofs[3] = (emu.gpu.ppu.bg_v_ofs[3] & !(mask & 0x1FF)) | (value & mask & 0x1FF)),
        (io16(0x20), |mask, value, emu| emu.gpu.ppu.bg_pa[0] = ((emu.gpu.ppu.bg_pa[0] as u16 & !mask) | (value & mask)) as i16),
        (io16(0x22), |mask, value, emu| emu.gpu.ppu.bg_pb[0] = ((emu.gpu.ppu.bg_pb[0] as u16 & !mask) | (value & mask)) as i16),
        (io16(0x24), |mask, value, emu| emu.gpu.ppu.bg_pc[0] = ((emu.gpu.ppu.bg_pc[0] as u16 & !mask) | (value & mask)) as i16),
        (io16(0x26), |mask, value, emu| emu.gpu.ppu.bg_pd[0] = ((emu.gpu.ppu.bg_pd[0] as u16 & !mask) | (value & mask)) as i16),
        (io32(0x28), |mask, value, emu| emu.gpu.ppu.set_bg_x(0, mask, value)),
        (io32(0x2C), |mask, value, emu| emu.gpu.ppu.set_bg_y(0, mask, value)),
        (io16(0x30), |mask, value, emu| emu.gpu.ppu.bg_pa[1] = ((emu.gpu.ppu.bg_pa[1] as u16 & !mask) | (value & mask)) as i16),
        (io16(0x32), |mask, value, emu| emu.gpu.ppu.bg_pb[1] = ((emu.gpu.ppu.bg_pb[1] as u16 & !mask) | (value & mask)) as i16),
        (io16(0x34), |mask, value, emu| emu.gpu.ppu.bg_pc[1] = ((emu.gpu.ppu.bg_pc[1] as u16 & !mask) | (value & mask)) as i16),
        (io16(0x36), |mask, value, emu| emu.gpu.ppu.bg_pd[1] = ((emu.gpu.ppu.bg_pd[1] as u16 & !mask) | (value & mask)) as i16),
        (io32(0x38), |mask, value, emu| emu.gpu.ppu.set_bg_x(1, mask, value)),
        (io32(0x3C), |mask, value, emu| emu.gpu.ppu.set_bg_y(1, mask, value)),
        (io16(0x40), |mask, value, emu| emu.gpu.ppu.win_h[0] = (emu.gpu.ppu.win_h[0] & !mask) | (value & mask)),
        (io16(0x42), |mask, value, emu| emu.gpu.ppu.win_h[1] = (emu.gpu.ppu.win_h[1] & !mask) | (value & mask)),
        (io16(0x44), |mask, value, emu| emu.gpu.ppu.win_v[0] = (emu.gpu.ppu.win_v[0] & !mask) | (value & mask)),
        (io16(0x46), |mask, value, emu| emu.gpu.ppu.win_v[1] = (emu.gpu.ppu.win_v[1] & !mask) | (value & mask)),
        (io16(0x48), |mask, value, emu| emu.gpu.ppu.win_in = (emu.gpu.ppu.win_in & !(mask & 0x3F3F)) | (value & mask & 0x3F3F)),
        (io16(0x4A), |mask, value, emu| emu.gpu.ppu.win_out = (emu.gpu.ppu.win_out & !(mask & 0x3F3F)) | (value & mask & 0x3F3F)),
        (io16(0x4C), |mask, value, emu| emu.gpu.ppu.mosaic = (emu.gpu.ppu.mosaic & !mask) | (value & mask)),
        (io16(0x50), |mask, value, emu| emu.gpu.ppu.bld_cnt = (emu.gpu.ppu.bld_cnt & !(mask & 0x3FFF)) | (value & mask & 0x3FFF)),
        (io16(0x52), |mask, value, emu| emu.gpu.ppu.bld_alpha = (emu.gpu.ppu.bld_alpha & !(mask & 0x1F1F)) | (value & mask & 0x1F1F)),
        (io16(0x54), |mask, value, emu| emu.gpu.ppu.bld_y = (emu.gpu.ppu.bld_y & !(mask & 0x1F)) | (value & mask & 0x1F)),
        (io16(0x60), |mask, value, emu| if mask & 0xFF != 0 { emu.apu.write_cnt_l(0, value as u8) }),
        (io16(0x62), |mask, value, emu| emu.apu.write_cnt_h(0, mask, value)),
        (io16(0x64), |mask, value, emu| emu.apu.write_cnt_x(0, mask, value)),
        (io16(0x68), |mask, value, emu| emu.apu.write_cnt_h(1, mask, value)),
        (io16(0x6C), |mask, value, emu| emu.apu.write_cnt_x(1, mask, value)),
        (io16(0x70), |mask, value, emu| if mask & 0xFF != 0 { emu.apu.write_cnt_l(2, value as u8) }),
        (io16(0x72), |mask, value, emu| emu.apu.write_cnt_h(2, mask, value)),
        (io16(0x74), |mask, value, emu| emu.apu.write_cnt_x(2, mask, value)),
        (io16(0x78), |mask, value, emu| emu.apu.write_cnt_h(3, mask, value)),
        (io16(0x7C), |mask, value, emu| emu.apu.write_cnt_x(3, mask, value)),
        (io16(0x80), |mask, value, emu| emu.apu.write_main_cnt_l(mask, value)),
        (io16(0x82), |mask, value, emu| emu.apu.write_main_cnt_h(mask, value)),
        (io16(0x84), |mask, value, emu| if mask & 0xFF != 0 { emu.apu.write_main_cnt_x(value as u8) }),
        (io16(0x88), |mask, value, emu| emu.apu.write_sound_bias(mask, value)),
        (io8(0x90), |value, emu| emu.apu.write_wave_ram(0, value)),
        (io8(0x91), |value, emu| emu.apu.write_wave_ram(1, value)),
        (io8(0x92), |value, emu| emu.apu.write_wave_ram(2, value)),
        (io8(0x93), |value, emu| emu.apu.write_wave_ram(3, value)),
        (io8(0x94), |value, emu| emu.apu.write_wave_ram(4, value)),
        (io8(0x95), |value, emu| emu.apu.write_wave_ram(5, value)),
        (io8(0x96), |value, emu| emu.apu.write_wave_ram(6, value)),
        (io8(0x97), |value, emu| emu.apu.write_wave_ram(7, value)),
        (io8(0x98), |value, emu| emu.apu.write_wave_ram(8, value)),
        (io8(0x99), |value, emu| emu.apu.write_wave_ram(9, value)),
        (io8(0x9A), |value, emu| emu.apu.write_wave_ram(10, value)),
        (io8(0x9B), |value, emu| emu.apu.write_wave_ram(11, value)),
        (io8(0x9C), |value, emu| emu.apu.write_wave_ram(12, value)),
        (io8(0x9D), |value, emu| emu.apu.write_wave_ram(13, value)),
        (io8(0x9E), |value, emu| emu.apu.write_wave_ram(14, value)),
        (io8(0x9F), |value, emu| emu.apu.write_wave_ram(15, value)),
        (io32(0xA0), |mask, value, emu| emu.apu.write_fifo(0, mask, value)),
        (io32(0xA4), |mask, value, emu| emu.apu.write_fifo(1, mask, value)),
        (io32(0xB0), |mask, value, emu| emu.dma_set_sad(0, mask, value)),
        (io32(0xB4), |mask, value, emu| emu.dma_set_dad(0, mask, value)),
        (io32(0xB8), |mask, value, emu| emu.dma_set_cnt(0, mask, value)),
        (io32(0xBC), |mask, value, emu| emu.dma_set_sad(1, mask, value)),
        (io32(0xC0), |mask, value, emu| emu.dma_set_dad(1, mask, value)),
        (io32(0xC4), |mask, value, emu| emu.dma_set_cnt(1, mask, value)),
        (io32(0xC8), |mask, value, emu| emu.dma_set_sad(2, mask, value)),
        (io32(0xCC), |mask, value, emu| emu.dma_set_dad(2, mask, value)),
        (io32(0xD0), |mask, value, emu| emu.dma_set_cnt(2, mask, value)),
        (io32(0xD4), |mask, value, emu| emu.dma_set_sad(3, mask, value)),
        (io32(0xD8), |mask, value, emu| emu.dma_set_dad(3, mask, value)),
        (io32(0xDC), |mask, value, emu| emu.dma_set_cnt(3, mask, value)),
        (io16(0x100), |mask, value, emu| emu.timers_set_cnt_l(0, mask, value)),
        (io16(0x102), |mask, value, emu| emu.timers_set_cnt_h(0, mask, value)),
        (io16(0x104), |mask, value, emu| emu.timers_set_cnt_l(1, mask, value)),
        (io16(0x106), |mask, value, emu| emu.timers_set_cnt_h(1, mask, value)),
        (io16(0x108), |mask, value, emu| emu.timers_set_cnt_l(2, mask, value)),
        (io16(0x10A), |mask, value, emu| emu.timers_set_cnt_h(2, mask, value)),
        (io16(0x10C), |mask, value, emu| emu.timers_set_cnt_l(3, mask, value)),
        (io16(0x10E), |mask, value, emu| emu.timers_set_cnt_h(3, mask, value)),
        (io16(0x132), |mask, value, emu| emu.input.set_key_cnt(mask, value)),
        (io16(0x200), |mask, value, emu| emu.cpu_set_ie(mask as u32, value as u32)),
        (io16(0x202), |mask, value, emu| emu.cpu_set_irf(mask as u32, value as u32)),
        (io16(0x204), |mask, value, emu| {
            let cpu_regs = &mut emu.cpu;
            cpu_regs.wait_cnt = (cpu_regs.wait_cnt & !mask) | (value & mask);
        }),
        (io8(0x208), |value, emu| emu.cpu_set_ime(value)),
        (io8(0x300), |value, emu| emu.cpu_set_post_flg(value)),
        (io8(0x301), |value, emu| emu.cpu_set_halt_cnt(value)),
    );
}
